#!/bin/sh

if [ "$1" = "--help" ]; then echo "
getmedia.sh

Pracuje se souborem a vyhleda adresy obrazku/zvuku

         -i	vypise adersy obrazku (.jpg, .png, .svg)
	 -s	vypise adresy zvuku (.wav, .mp3, .ogg)"; exit; fi;

if [ "$1" = "-s" ]; then
	grep  'http[^ ]*\.wav' $2;
	grep  'http[^ ]*\.mp3' $2;
	grep  'http[^ ]*\.ogg' $2;
fi;

if [ "$1" = "-i" ]; then
	grep  'http[^ ]*\.jpg' $2;
        grep  'http[^ ]*\.png' $2;
        grep  'http[^ ]*\.svg' $2;
fi;

if [ "$1" = *".html" ]; then
	grep  'http[^ ]*\.wav' $1;
        grep  'http[^ ]*\.mp3' $1;
        grep  'http[^ ]*\.ogg' $1;
	grep  'http[^ ]*\.jpg' $1;
        grep  'http[^ ]*\.png' $1;
        grep  'http[^ ]*\.svg' $1;
fi;


